package com.ibm.icu.text;

import com.ibm.icu.text.ListFormatter;

class ListFormatterData {
   static void load() {
      ListFormatter.add("af", new String[]{"{0} en {1}", "{0}, {1}", "{0}, {1}", "{0} en {1}"});
      ListFormatter.add("am", new String[]{"{0} እና {1}", "{0}, {1}", "{0}, {1}", "{0}, እና {1}"});
      ListFormatter.add("ar", new String[]{"{0} و {1}", "{0}، {1}", "{0}، {1}", "{0}، و {1}"});
      ListFormatter.add("bg", new String[]{"{0} и {1}", "{0}, {1}", "{0}, {1}", "{0} и {1}"});
      ListFormatter.add("bn", new String[]{"{0} এবং {1}", "{0}, {1}", "{0}, {1}", "{0}, এবং {1}"});
      ListFormatter.add("bs", new String[]{"{0} i {1}", "{0}, {1}", "{0}, {1}", "{0} i {1}"});
      ListFormatter.add("ca", new String[]{"{0} i {1}", "{0}, {1}", "{0}, {1}", "{0} i {1}"});
      ListFormatter.add("cs", new String[]{"{0} a {1}", "{0}, {1}", "{0}, {1}", "{0} a {1}"});
      ListFormatter.add("da", new String[]{"{0} og {1}", "{0}, {1}", "{0}, {1}", "{0} og {1}"});
      ListFormatter.add("de", new String[]{"{0} und {1}", "{0}, {1}", "{0}, {1}", "{0} und {1}"});
      ListFormatter.add("ee", new String[]{"{0} kple {1}", "{0}, {1}", "{0}, {1}", "{0}, kple {1}"});
      ListFormatter.add("el", new String[]{"{0} και {1}", "{0}, {1}", "{0}, {1}", "{0} και {1}"});
      ListFormatter.add("en", new String[]{"{0} and {1}", "{0}, {1}", "{0}, {1}", "{0}, and {1}"});
      ListFormatter.add("es", new String[]{"{0} y {1}", "{0}, {1}", "{0}, {1}", "{0} y {1}"});
      ListFormatter.add("et", new String[]{"{0} ja {1}", "{0}, {1}", "{0}, {1}", "{0} ja {1}"});
      ListFormatter.add("eu", new String[]{"{0} eta {1}", "{0}, {1}", "{0}, {1}", "{0} eta {1}"});
      ListFormatter.add("fa", new String[]{"{0} و {1}", "{0}،\u200f {1}", "{0}،\u200f {1}", "{0}، و {1}"});
      ListFormatter.add("fi", new String[]{"{0} ja {1}", "{0}, {1}", "{0}, {1}", "{0} ja {1}"});
      ListFormatter.add("fil", new String[]{"{0} at {1}", "{0}, {1}", "{0}, {1}", "{0} at {1}"});
      ListFormatter.add("fo", new String[]{"{0} og {1}", "{0}, {1}", "{0}, {1}", "{0} og {1}"});
      ListFormatter.add("fr", new String[]{"{0} et {1}", "{0}, {1}", "{0}, {1}", "{0} et {1}"});
      ListFormatter.add("fur", new String[]{"{0} e {1}", "{0}, {1}", "{0}, {1}", "{0} e {1}"});
      ListFormatter.add("gd", new String[]{"{0} agus {1}", "{0}, {1}", "{0}, {1}", "{0}, agus {1}"});
      ListFormatter.add("gl", new String[]{"{0} e {1}", "{0}, {1}", "{0}, {1}", "{0} e {1}"});
      ListFormatter.add("gsw", new String[]{"{0} und {1}", "{0}, {1}", "{0}, {1}", "{0} und {1}"});
      ListFormatter.add("gu", new String[]{"{0} અને {1}", "{0}, {1}", "{0}, {1}", "{0} અને {1}"});
      ListFormatter.add("he", new String[]{"{0} ו-{1}", "{0}, {1}", "{0}, {1}", "{0} ו-{1}"});
      ListFormatter.add("hi", new String[]{"{0} और {1}", "{0}, {1}", "{0}, {1}", "{0}, और {1}"});
      ListFormatter.add("hr", new String[]{"{0} i {1}", "{0}, {1}", "{0}, {1}", "{0} i {1}"});
      ListFormatter.add("hu", new String[]{"{0} és {1}", "{0}, {1}", "{0}, {1}", "{0} és {1}"});
      ListFormatter.add("id", new String[]{"{0} dan {1}", "{0}, {1}", "{0}, {1}", "{0}, dan {1}"});
      ListFormatter.add("is", new String[]{"{0} og {1}", "{0}, {1}", "{0}, {1}", "{0} og {1}"});
      ListFormatter.add("it", new String[]{"{0} e {1}", "{0}, {1}", "{0}, {1}", "{0}, e {1}"});
      ListFormatter.add("ja", new String[]{"{0}、{1}", "{0}、{1}", "{0}、{1}", "{0}、{1}"});
      ListFormatter.add("ka", new String[]{"{0} და {1}", "{0}, {1}", "{0}, {1}", "{0} და {1}"});
      ListFormatter.add("kea", new String[]{"{0} y {1}", "{0}, {1}", "{0}, {1}", "{0} y {1}"});
      ListFormatter.add("kl", new String[]{"{0} aamma {1}", "{0} aamma {1}", "{0}, {1}", "{0}, {1}"});
      ListFormatter.add("kn", new String[]{"{0} ಮತ್ತು {1}", "{0}, {1}", "{0}, {1}", "{0}, ಮತ್ತು {1}"});
      ListFormatter.add("ko", new String[]{"{0} 및 {1}", "{0}, {1}", "{0}, {1}", "{0} 및 {1}"});
      ListFormatter.add("ksh", new String[]{"{0} un {1}", "{0}, {1}", "{0}, {1}", "{0} un {1}"});
      ListFormatter.add("lt", new String[]{"{0} ir {1}", "{0}, {1}", "{0}, {1}", "{0} ir {1}"});
      ListFormatter.add("lv", new String[]{"{0} un {1}", "{0}, {1}", "{0}, {1}", "{0} un {1}"});
      ListFormatter.add("ml", new String[]{"{0} കൂടാതെ {1}", "{0}, {1}", "{0}, {1}", "{0}, {1} എന്നിവ"});
      ListFormatter.add("mr", new String[]{"{0} आणि {1}", "{0}, {1}", "{0}, {1}", "{0} आणि {1}"});
      ListFormatter.add("ms", new String[]{"{0} dan {1}", "{0}, {1}", "{0}, {1}", "{0}, dan {1}"});
      ListFormatter.add("nb", new String[]{"{0} og {1}", "{0}, {1}", "{0}, {1}", "{0} og {1}"});
      ListFormatter.add("nl", new String[]{"{0} en {1}", "{0}, {1}", "{0}, {1}", "{0} en {1}"});
      ListFormatter.add("nn", new String[]{"{0} og {1}", "{0}, {1}", "{0}, {1}", "{0} og {1}"});
      ListFormatter.add("pl", new String[]{"{0} i {1}", "{0}; {1}", "{0}; {1}", "{0} i {1}"});
      ListFormatter.add("pt", new String[]{"{0} e {1}", "{0}, {1}", "{0}, {1}", "{0} e {1}"});
      ListFormatter.add("ro", new String[]{"{0} şi {1}", "{0}, {1}", "{0}, {1}", "{0} şi {1}"});
      ListFormatter.add("", new String[]{"{0}, {1}", "{0}, {1}", "{0}, {1}", "{0}, {1}"});
      ListFormatter.add("ru", new String[]{"{0} и {1}", "{0}, {1}", "{0}, {1}", "{0} и {1}"});
      ListFormatter.add("se", new String[]{"{0} ja {1}", "{0}, {1}", "{0}, {1}", "{0} ja {1}"});
      ListFormatter.add("sk", new String[]{"{0} a {1}", "{0}, {1}", "{0}, {1}", "{0} a {1}"});
      ListFormatter.add("sl", new String[]{"{0} in {1}", "{0}, {1}", "{0}, {1}", "{0} in {1}"});
      ListFormatter.add("sr", new String[]{"{0} и {1}", "{0}, {1}", "{0}, {1}", "{0} и {1}"});
      ListFormatter.add("sr_Cyrl", new String[]{"{0} и {1}", "{0}, {1}", "{0}, {1}", "{0} и {1}"});
      ListFormatter.add("sr_Latn", new String[]{"{0} i {1}", "{0}, {1}", "{0}, {1}", "{0} i {1}"});
      ListFormatter.add("sv", new String[]{"{0} och {1}", "{0}, {1}", "{0}, {1}", "{0} och {1}"});
      ListFormatter.add("sw", new String[]{"{0} na {1}", "{0}, {1}", "{0}, {1}", "{0}, na {1}"});
      ListFormatter.add("ta", new String[]{"{0} மற்றும் {1}", "{0}, {1}", "{0}, {1}", "{0} மற்றும் {1}"});
      ListFormatter.add("te", new String[]{"{0} మరియు {1}", "{0}, {1}", "{0}, {1}", "{0} మరియు {1}"});
      ListFormatter.add("th", new String[]{"{0}และ{1}", "{0} {1}", "{0} {1}", "{0} และ{1}"});
      ListFormatter.add("tr", new String[]{"{0} ve {1}", "{0}, {1}", "{0}, {1}", "{0} ve {1}"});
      ListFormatter.add("uk", new String[]{"{0} та {1}", "{0}, {1}", "{0}, {1}", "{0} та {1}"});
      ListFormatter.add("ur", new String[]{"{0} اور {1}", "{0}، {1}", "{0}، {1}", "{0}، اور {1}"});
      ListFormatter.add("vi", new String[]{"{0} và {1}", "{0}, {1}", "{0}, {1}", "{0} và {1}"});
      ListFormatter.add("wae", new String[]{"{0} und {1}", "{0}, {1}", "{0}, {1}", "{0} und {1}"});
      ListFormatter.add("zh", new String[]{"{0}和{1}", "{0}、{1}", "{0}、{1}", "{0}和{1}"});
      ListFormatter.add("zh", new String[]{"{0}和{1}", "{0}、{1}", "{0}、{1}", "{0}和{1}"});
      ListFormatter.add("zu", new String[]{"I-{0} ne-{1}", "{0}, {1}", "{0}, {1}", "{0}, no-{1}"});
   }
}
